### PR TITLE
watchdog version up and add minimal template using r-minimal image

### PR DESCRIPTION
**Pull request by mrchypark**
update of-watchdog 0.7.2 to 0.7.6 
update watchdog 0.18.1 to 0.18.10
add minimal version template based on alpine linux

### CODE REVIEW

**Comment by psolymos** [comment]
Hi @mrchypark I reviewed you PR a few days ago but I have been traveling since then. Here is wat I think:
- Upgrading to newer of-watchdog version makes sense. 
- I really like the minimal template, but it might make sense to make a separate PR for that one and 
- leave the RestRserve template for later: there is potential but it is not working yet.

**Comment by mrchypark** [comment]
I agree. I'm not good at PR.

I'm trying to separate PR later. Thank you for response.

**Comment by psolymos** [comment]
I appreciate your work, and I am sure you'll get better at PRs! Here is what I would suggest: focus on the 1st 2 parts of my previous comments (1: updating of-watchdog versions, 2: r-minimal template).

I am also working on a CONTRIBUTING guide that'll make things easier next time.

Thanks.

**Comment by mrchypark** [comment]
I add 2 PR. ;) Thank you for your guide.

**Comment by psolymos** [comment]
Thanks. See PRs #15  and #16

**Pull request closed without merging**
